# -*- coding: utf-8 -*-
"""Qadir

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_CB_sKbNwcQ0JpUk8kqNnplsu0iD4Pyd
"""

import os
import zipfile
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras import layers, models

zip_path = "/content/archive.zip"
extract_path = "/content/cat_dog_dataset"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Dataset extracted successfully!")
print("Folders:", os.listdir(extract_path))

IMG_SIZE = (128, 128)
BATCH_SIZE = 32
SEED = 42

image_extensions = (".jpg", ".jpeg", ".png")
dataset_dir = None
max_images = 0

for root, dirs, files in os.walk(extract_path):
    total_images = 0
    class_folders = []

    for d in dirs:
        folder_path = os.path.join(root, d)
        image_files = [
            f for f in os.listdir(folder_path)
            if f.lower().endswith(image_extensions)
        ]

        if len(image_files) > 0:
            class_folders.append(d)
            total_images += len(image_files)

    if len(class_folders) >= 2 and total_images > max_images:
        dataset_dir = root
        max_images = total_images

print("Dataset folder:", dataset_dir)
print("Class folders:", os.listdir(dataset_dir))

train_ds = tf.keras.utils.image_dataset_from_directory(
    dataset_dir,
    validation_split=0.2,
    subset="training",
    seed=SEED,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE
)

val_ds = tf.keras.utils.image_dataset_from_directory(
    dataset_dir,
    validation_split=0.2,
    subset="validation",
    seed=SEED,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE
)

class_names = train_ds.class_names
num_classes = len(class_names)

print("Classes:", class_names)
print("Total Classes:", num_classes)

plt.figure(figsize=(10, 8))

for images, labels in train_ds.take(1):
    for i in range(9):
        plt.subplot(3, 3, i + 1)
        plt.imshow(images[i].numpy().astype("uint8"))
        plt.title(class_names[int(labels[i])])
        plt.axis("off")

plt.show()

cnn_model = models.Sequential([
    layers.Input(shape=(128, 128, 3)),
    layers.Rescaling(1./255),

    layers.Conv2D(32, (3, 3), activation='relu'),
    layers.MaxPooling2D(),

    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D(),

    layers.Conv2D(128, (3, 3), activation='relu'),
    layers.MaxPooling2D(),

    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.3),
    layers.Dense(num_classes, activation='softmax')
])

cnn_model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

cnn_model.summary()

history = cnn_model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=5
)

print("CNN model training completed successfully!")

plt.figure(figsize=(14, 10))

for images, labels in val_ds.take(1):
    predictions = cnn_model.predict(images)

    for i in range(12):
        plt.subplot(3, 4, i + 1)

        img = images[i].numpy().astype("uint8")
        actual_label = class_names[int(labels[i].numpy())]

        predicted_index = np.argmax(predictions[i])
        predicted_label = class_names[predicted_index]
        confidence = np.max(predictions[i]) * 100

        plt.imshow(img)
        plt.axis("off")
        plt.title(
            f"Actual: {actual_label}\nPredicted: {predicted_label}\nConfidence: {confidence:.2f}%",
            fontsize=9
        )

plt.tight_layout()
plt.show()